name: Latest blog post workflow
on:
  repository_dispatch:
    types: [contentful.deploy]
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/wait-action@master
      - uses: MateuszSzostek/Gatsby-Template@main
        with:
          commit_message: "Updated README with latest blog posts"
          
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - name: Fetch resources
        run: ./scripts/fetch-resources.sh

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: path/to/file
            commit-msg: Update resources
            github-token: ${{ secrets.GITHUB_TOKEN }}
     
